# Base configs
baseurl: "https://mosiehillis.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-8THYDCWVPG"

# UI configs
title: "Photography by Mosie Hillis"
subtitle: "A Sample of My Work"
author: "Mosie Hillis"
web_design: "AJ"
header:
 title: "Photography"
 subtitle: "by Mosie Hillis"
footer:
 name: "Now booking through 2022!"
 bio: "Reach out for availability and logistics."
social_urls:
  facebook: "https://www.facebook.com/1446553751"
  twitter: "https://www.twitter.com/mozehillis"
  instagram: "https://www.instagram.com/mozehillis"
