# Base configs
baseurl: "https://mosiehillis.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-8THYDCWVPG"

# UI configs
title: "Concert Photography"
subtitle: "A Sample of My Work"
author: "Mosie Hillis"
web_design: "AJ"
header:
 title: "Concert Photography"
 subtitle: "by Mosie Hillis"
footer:
 name: "Now booking through 2022!"
 bio: "Reach out for availability and logistics."
social_urls:
  facebook: "https://www.facebook.com/1446553751"
  twitter: "https://www.twitter.com/mozehillis"
  instagram: "https://www.instagram.com/mozehillis"

exclude: 
  - ".bundle"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - "CNAME"
  - "node_modules"
  - "gulpfile.js"
  - "npmfile.js"
  - "package.json"
  - "package-lock.json"
  - "README.md"

# Config which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif_display: '[{"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'

